### ISSUE TITLE
Test two LiveData consequent emissions in ShotViewModel 

### ISSUE THREAD

**Issue by manuelvicnt** [android/plaid#655]
There's a test missing in ShortViewModelTest.

We want to test that the ViewModel emits two uiModel objects. The first one as a fast emission as soon as the VM is created and then, after a new coroutine in the background makes some processing, the second value.

Maybe there's a way we can control the Coroutine with a `ContinuationInterceptor`? We don't want to change the VM behaviour just for the sake of the tests.

**Comment by ashdavies** [comment]
Can you use `TestCoroutineContext.triggerActions()`?

**Comment by manuelvicnt** [comment]
I tried this but doesn't work

```
    @UseExperimental(ObsoleteCoroutinesApi::class)
    @Test
    fun loadShot_emitsTwoUiModels() {
        val testContext = TestCoroutineContext()
        runBlocking(testContext) {
            // Given that the repo successfully returns the requested shot
            // When view model is constructed
            testContext.cancelAllActions()

            val viewModel = withViewModel()

            // Then a shotUiModel is present
            val slowResult: ShotUiModel? = LiveDataTestUtil.getValue(viewModel.shotUiModel)
            assertNotNull(slowResult)
            assertTrue(slowResult?.formattedDescription!!.isEmpty())

            testContext.triggerActions()

            // Then a shotUiModel is present
            val fastResult: ShotUiModel? = LiveDataTestUtil.getValue(viewModel.shotUiModel)
            assertNotNull(fastResult)
            assertTrue(slowResult?.formattedDescription!!.isNotEmpty())
        }
    }
```

Am I misusing it? should that work? @ashdavies

**Comment by ashdavies** [comment]
This is how I would expect to use it, `cancelAllActions` may not be necessary, I'll try and have a go myself this evening, but if it's not working for you, perhaps it's not going to be the right solution 😢

**Comment by ashdavies** [comment]
Looking over it again I think I can see what's wrong, it's not enough that you run the test code within the `TestCoroutineContext` (in fact I think that's unnecessary), the context needs to be provided to the `ViewModel` to ensure that the coroutine launched after the fast emission uses this context instead of the `Unconfined` that has been injected via `CoroutinesDispatcherProvider`, which would cause it to execute immediately.

The issue here is actually the difference in Coroutine usage, since `TestCoroutineContext` isn't a `Dispatcher` it can't be used as `CoroutineDispatcher` but needs to be the provided `CoroutineContext` instead (this is what @objcode is working on [here](https://github.com/Kotlin/kotlinx.coroutines/pull/890).
