### ISSUE TITLE
Dribbble `ShotActivity` status/nav bar fading is broken

### ISSUE THREAD

**Issue by nickbutcher** [android/plaid#722]
This screen used the `ChromeFader` class to fade the status/nav bar if the screen is being drag dismissed downward/upward respectively. This appears to be broken and instantly makes them transparent as soon as a drag starts.

The `ChromeFader` class appears to be working fine elsewhere e.g. DN `StoryActivity` so seems specific to this screen. Perhaps the move to injecting this class?

**Comment by nickbutcher** [comment]
Watch the status bar here:

![broken_status_bar_fade](https://user-images.githubusercontent.com/352556/59361263-78b7d580-8d29-11e9-8555-daebfc2c32b9.gif)

**Comment by limdale** [comment]
I took a look at this, looks like it's happening because the injection of ChromeFader happening before the activity setContentView (because of the lazy delegate). The ChromeFader sees that the activity has no content view yet and sets status bar alpha to 0.

You could either:
1) inflate the activity right away (will have to make `binding` a `lateinit var` and remove delegate)
2) reference the binding before injecting Dagger to trigger the lazy delegate
3) remove the `ChromeFader` from Dagger

I gave a shot at the third solution here: #739
